language: ruby
rvm:
  - 2.4.0
services:
  - mysql
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - cp config/database.travis.yml config/database.yml
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - npm install -g webpack yarn
  - yarn add bootstrap jquery
script:
  - export RAILS_ENV=test
  - bundle exec rails db:create db:migrate
  - bundle exec rails db:test:prepare
  - bundle exec rspec spec

addons:
  code_climate:
    repo_token: c5ed4be4330005d41849fe507a4f4d71215189cca8c89d996516faf54c45b592
